/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Questions;

import DatabaseManager.mysqlConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JPanel;

/**
 *
 * @author EJ
 */
public class JavaQuestions extends javax.swing.JInternalFrame {
    
    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st = null;
    private int itr = 2;
    /**
     * Creates new form JavaQuestions
     */
    public JavaQuestions() {
        initComponents();
        
    }
    
     public JavaQuestions(String name, String student_number){
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbl_name.setText(name);
        lbl_student_number.setText(student_number);
        Timer();
    }
    
    private void getData(JPanel panel1, JPanel panel2){
        panel1.removeAll();
        panel1.add(panel2);
        panel1.repaint();
        panel1.revalidate();
    }
    
    private void Timer(){
        Timer myTimer = new Timer();
        TimerTask task = new TimerTask(){
           int second = 91;
           public void run(){
                second--;
                lbl_time.setText(Integer.toString(second));
                if(second == 0){
                    myTimer.cancel();
                    nextFrame();
                }   
           }
        };
        myTimer.scheduleAtFixedRate(task, 0, 1000);
    }
    
     private void insertData(int score){
        connection = mysqlConnection.dbConnector();
        String subject = lbl_subject.getText();
        try{
            String sql = "insert into Exam (`Student #`, Date,  Score, `Course Code`) values "
                    + "(?,?,?, (SELECT `Course Code` from course where subject = '"+subject+"'))";
            pst = connection.prepareStatement(sql);
            pst.setString(1, lbl_student_number.getText());
            pst.setString(2, null);
            pst.setInt(3, score);
            
            pst.execute();
            pst.close();
            }catch(Exception e){
                e.printStackTrace();
            }
    }
     
     public void nextFrame(){
        SqlQuestions sq = new SqlQuestions(lbl_name.getText(), lbl_student_number.getText());
        sq.setVisible(true);
        this.getDesktopPane().add(sq);
        this.dispose();
     }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panel_question_head = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        lbl_student_number = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        lbl_subject = new javax.swing.JLabel();
        lbl_question_number = new javax.swing.JLabel();
        btn_next = new javax.swing.JButton();
        panel_question_body = new javax.swing.JPanel();
        panel_question_body_1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        radioBtn_answer_1 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        panel_question_body_2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        radioBtn_answer_2 = new javax.swing.JRadioButton();
        panel_question_body_3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        radioBtn_answer_3 = new javax.swing.JRadioButton();
        panel_question_body_4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        radioBtn_answer_4 = new javax.swing.JRadioButton();
        panel_question_body_5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        radioBtn_answer_5 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();

        setMinimumSize(new java.awt.Dimension(540, 390));
        setPreferredSize(new java.awt.Dimension(540, 390));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        panel_question_head.setBackground(new java.awt.Color(204, 204, 0));
        panel_question_head.setMaximumSize(new java.awt.Dimension(278, 82));
        panel_question_head.setMinimumSize(new java.awt.Dimension(278, 82));

        lbl_name.setFont(new java.awt.Font("Forte", 0, 11)); // NOI18N
        lbl_name.setText("Student name");

        lbl_student_number.setFont(new java.awt.Font("Forte", 0, 11)); // NOI18N
        lbl_student_number.setText("Student #");

        jLabel3.setFont(new java.awt.Font("Forte", 0, 11)); // NOI18N
        jLabel3.setText("Time left:");

        lbl_time.setFont(new java.awt.Font("Forte", 1, 13)); // NOI18N
        lbl_time.setText("time");

        lbl_subject.setFont(new java.awt.Font("Forte", 1, 18)); // NOI18N
        lbl_subject.setText("Java");

        lbl_question_number.setFont(new java.awt.Font("Forte", 1, 18)); // NOI18N
        lbl_question_number.setText("Question # 1");

        btn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next_icon_1.png"))); // NOI18N
        btn_next.setContentAreaFilled(false);
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_question_headLayout = new javax.swing.GroupLayout(panel_question_head);
        panel_question_head.setLayout(panel_question_headLayout);
        panel_question_headLayout.setHorizontalGroup(
            panel_question_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_headLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_question_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_question_headLayout.createSequentialGroup()
                        .addGroup(panel_question_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_student_number)
                            .addGroup(panel_question_headLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_time)))
                        .addGap(122, 122, 122)
                        .addComponent(lbl_question_number))
                    .addGroup(panel_question_headLayout.createSequentialGroup()
                        .addComponent(lbl_name)
                        .addGap(147, 147, 147)
                        .addComponent(lbl_subject)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_next))
        );
        panel_question_headLayout.setVerticalGroup(
            panel_question_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_question_headLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_question_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_next)
                    .addGroup(panel_question_headLayout.createSequentialGroup()
                        .addGroup(panel_question_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_name)
                            .addComponent(lbl_subject))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_question_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_question_number)
                            .addGroup(panel_question_headLayout.createSequentialGroup()
                                .addComponent(lbl_student_number)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_question_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(lbl_time)))))))
        );

        panel_question_body.setBackground(new java.awt.Color(204, 153, 0));
        panel_question_body.setLayout(new java.awt.CardLayout());

        panel_question_body_1.setBackground(new java.awt.Color(204, 153, 0));

        jLabel7.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jLabel7.setText("Which of the following asymptotic notation is the worst among all");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton1.setText("2O(n)");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton2.setText("nO(1)  ");

        buttonGroup1.add(radioBtn_answer_1);
        radioBtn_answer_1.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        radioBtn_answer_1.setText("O(n3)");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton5.setText("O(n+9378)");

        javax.swing.GroupLayout panel_question_body_1Layout = new javax.swing.GroupLayout(panel_question_body_1);
        panel_question_body_1.setLayout(panel_question_body_1Layout);
        panel_question_body_1Layout.setHorizontalGroup(
            panel_question_body_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_question_body_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(radioBtn_answer_1)
                    .addComponent(jRadioButton5))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panel_question_body_1Layout.setVerticalGroup(
            panel_question_body_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtn_answer_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addGap(22, 22, 22))
        );

        panel_question_body.add(panel_question_body_1, "card2");

        panel_question_body_2.setBackground(new java.awt.Color(204, 153, 0));

        jLabel8.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jLabel8.setText("After each iteration in bubble sort");

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton6.setText("Neither A or B are true.");

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton7.setText("Both A & B are true.");

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton8.setText("one less comparison is made in the next iteration.");

        buttonGroup2.add(radioBtn_answer_2);
        radioBtn_answer_2.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        radioBtn_answer_2.setText("at least one element is at its sorted position.");

        javax.swing.GroupLayout panel_question_body_2Layout = new javax.swing.GroupLayout(panel_question_body_2);
        panel_question_body_2.setLayout(panel_question_body_2Layout);
        panel_question_body_2Layout.setHorizontalGroup(
            panel_question_body_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_question_body_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8)
                    .addComponent(radioBtn_answer_2))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        panel_question_body_2Layout.setVerticalGroup(
            panel_question_body_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(radioBtn_answer_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6)
                .addGap(22, 22, 22))
        );

        panel_question_body.add(panel_question_body_2, "card2");

        panel_question_body_3.setBackground(new java.awt.Color(204, 153, 0));

        jLabel9.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jLabel9.setText("<html>How many swaps are required to sort the given array using<br \\> bubble sort - { 2, 5, 1, 3, 4}");

        buttonGroup3.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton10.setText("7");

        buttonGroup3.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton11.setText("6");

        buttonGroup3.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton12.setText("5");

        buttonGroup3.add(radioBtn_answer_3);
        radioBtn_answer_3.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        radioBtn_answer_3.setText("4");

        javax.swing.GroupLayout panel_question_body_3Layout = new javax.swing.GroupLayout(panel_question_body_3);
        panel_question_body_3.setLayout(panel_question_body_3Layout);
        panel_question_body_3Layout.setHorizontalGroup(
            panel_question_body_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_question_body_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12)
                    .addComponent(radioBtn_answer_3))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        panel_question_body_3Layout.setVerticalGroup(
            panel_question_body_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioBtn_answer_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton10)
                .addGap(22, 22, 22))
        );

        panel_question_body.add(panel_question_body_3, "card2");

        panel_question_body_4.setBackground(new java.awt.Color(204, 153, 0));

        jLabel10.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jLabel10.setText("<html>For a binary search algorithm to work, it is necessary that the <br \\>array (list) must be");

        buttonGroup4.add(jRadioButton14);
        jRadioButton14.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton14.setText("Popped out of stack");

        buttonGroup4.add(jRadioButton15);
        jRadioButton15.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton15.setText("In a heap");

        buttonGroup4.add(jRadioButton16);
        jRadioButton16.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton16.setText("Unsorted");

        buttonGroup4.add(radioBtn_answer_4);
        radioBtn_answer_4.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        radioBtn_answer_4.setText("Sorted");

        javax.swing.GroupLayout panel_question_body_4Layout = new javax.swing.GroupLayout(panel_question_body_4);
        panel_question_body_4.setLayout(panel_question_body_4Layout);
        panel_question_body_4Layout.setHorizontalGroup(
            panel_question_body_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_question_body_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton16)
                    .addComponent(radioBtn_answer_4))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        panel_question_body_4Layout.setVerticalGroup(
            panel_question_body_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioBtn_answer_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton14)
                .addGap(22, 22, 22))
        );

        panel_question_body.add(panel_question_body_4, "card2");

        panel_question_body_5.setBackground(new java.awt.Color(204, 153, 0));

        jLabel11.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jLabel11.setText("Tower of hanoi is a classic example of");

        buttonGroup5.add(radioBtn_answer_5);
        radioBtn_answer_5.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        radioBtn_answer_5.setText("Both A & B");

        buttonGroup5.add(jRadioButton19);
        jRadioButton19.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton19.setText("B but not A");

        buttonGroup5.add(jRadioButton20);
        jRadioButton20.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton20.setText("recursive approach");

        buttonGroup5.add(jRadioButton21);
        jRadioButton21.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton21.setText("divide and conquer");

        javax.swing.GroupLayout panel_question_body_5Layout = new javax.swing.GroupLayout(panel_question_body_5);
        panel_question_body_5.setLayout(panel_question_body_5Layout);
        panel_question_body_5Layout.setHorizontalGroup(
            panel_question_body_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_question_body_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(radioBtn_answer_5)
                    .addComponent(jRadioButton19)
                    .addComponent(jRadioButton20)
                    .addComponent(jRadioButton21))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        panel_question_body_5Layout.setVerticalGroup(
            panel_question_body_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jRadioButton21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtn_answer_5)
                .addGap(22, 22, 22))
        );

        panel_question_body.add(panel_question_body_5, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_question_body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_question_head, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_question_head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_question_body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(540, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
        lbl_question_number.setText("Question # " + itr);
        if(itr == 2){
            getData(panel_question_body, panel_question_body_2);
        }
        else if(itr == 3){
            getData(panel_question_body, panel_question_body_3);
        }
        else if(itr == 4){
            getData(panel_question_body, panel_question_body_4);
        }
        else if(itr == 5){
            getData(panel_question_body, panel_question_body_5);
        }
        else{
            int score = 0;

            if(radioBtn_answer_1.isSelected()){
                score++;
            }
            if(radioBtn_answer_2.isSelected()){
                score++;
            }
            if(radioBtn_answer_3.isSelected()){
                score++;
            }
            if(radioBtn_answer_4.isSelected()){
                score++;
            }
            if(radioBtn_answer_5.isSelected()){
                score++;
            }
            
            insertData(score);
            nextFrame();
        }
        itr++;
    }//GEN-LAST:event_btn_nextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_next;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_question_number;
    private javax.swing.JLabel lbl_student_number;
    private javax.swing.JLabel lbl_subject;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JPanel panel_question_body;
    private javax.swing.JPanel panel_question_body_1;
    private javax.swing.JPanel panel_question_body_2;
    private javax.swing.JPanel panel_question_body_3;
    private javax.swing.JPanel panel_question_body_4;
    private javax.swing.JPanel panel_question_body_5;
    private javax.swing.JPanel panel_question_head;
    private javax.swing.JRadioButton radioBtn_answer_1;
    private javax.swing.JRadioButton radioBtn_answer_2;
    private javax.swing.JRadioButton radioBtn_answer_3;
    private javax.swing.JRadioButton radioBtn_answer_4;
    private javax.swing.JRadioButton radioBtn_answer_5;
    // End of variables declaration//GEN-END:variables
}
