/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Questions;

import DatabaseManager.mysqlConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JPanel;

/**
 *
 * @author EJ
 */
public class SqlQuestions extends javax.swing.JInternalFrame {
    
    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st = null;
    private int itr = 2;
    /**
     * Creates new form SQL
     */
    public SqlQuestions() {
        initComponents();
    }
    
    public SqlQuestions(String name, String id) {
        initComponents();
        Timer();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbl_name.setText(name);
        lbl_student_number.setText(id);
    }
    
    private void getData(JPanel panel1, JPanel panel2){
        panel1.removeAll();
        panel1.add(panel2);
        panel1.repaint();
        panel1.revalidate();
    }
    
    private void Timer(){
        Timer myTimer = new Timer();
        TimerTask task = new TimerTask(){
           int second = 91;
           public void run(){
                second--;
                lbl_time.setText(Integer.toString(second));
                if(second == 0){
                    myTimer.cancel();
                   nextFrame();
                }
           }
        };
        myTimer.scheduleAtFixedRate(task, 0, 1000);
    }
    
     private void insertData(int score){
        connection = mysqlConnection.dbConnector();
        String subject = lbl_subject.getText();
        try{
            String sql = "insert into Exam (`Student #`, Date,  Score, `Course Code`) values "
                    + "(?,?,?, (SELECT `Course Code` from course where subject = '"+subject+"'))";
            pst = connection.prepareStatement(sql);
            pst.setString(1, lbl_student_number.getText());
            pst.setString(2, null);
            pst.setInt(3, score);
            
            pst.execute();
            pst.close();
            }catch(Exception e){
                e.printStackTrace();
            }
    }
     
    public void nextFrame(){
        DatabaseQuestions dq = new DatabaseQuestions(lbl_name.getText(), lbl_student_number.getText());
        dq.setVisible(true);
        this.getDesktopPane().add(dq);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panel_question_head = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        lbl_student_number = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        lbl_subject = new javax.swing.JLabel();
        lbl_question_number = new javax.swing.JLabel();
        btn_next = new javax.swing.JButton();
        panel_question_body = new javax.swing.JPanel();
        panel_question_body_1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        radioBtn_answer_1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        radioBtn_3 = new javax.swing.JRadioButton();
        radioBtn_answer_1512 = new javax.swing.JRadioButton();
        panel_question_body_2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        radioBtn_answer_2 = new javax.swing.JRadioButton();
        panel_question_body_3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        radioBtn_answer_3 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        radioBtn_4 = new javax.swing.JRadioButton();
        panel_question_body_4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        radioBtn_answer_4 = new javax.swing.JRadioButton();
        radioBtn09 = new javax.swing.JRadioButton();
        panel_question_body_5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        radioBtn_answer_5 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();

        setMaximumSize(new java.awt.Dimension(540, 390));
        setMinimumSize(new java.awt.Dimension(540, 390));
        setPreferredSize(new java.awt.Dimension(540, 390));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        panel_question_head.setBackground(new java.awt.Color(204, 204, 0));
        panel_question_head.setMaximumSize(new java.awt.Dimension(278, 82));
        panel_question_head.setMinimumSize(new java.awt.Dimension(278, 82));

        lbl_name.setFont(new java.awt.Font("Forte", 0, 11)); // NOI18N
        lbl_name.setText("Student name");

        lbl_student_number.setFont(new java.awt.Font("Forte", 0, 11)); // NOI18N
        lbl_student_number.setText("Student #");

        jLabel3.setFont(new java.awt.Font("Forte", 0, 11)); // NOI18N
        jLabel3.setText("Time left:");

        lbl_time.setFont(new java.awt.Font("Forte", 1, 13)); // NOI18N
        lbl_time.setText("time");

        lbl_subject.setFont(new java.awt.Font("Forte", 1, 18)); // NOI18N
        lbl_subject.setText("SQL");

        lbl_question_number.setFont(new java.awt.Font("Forte", 1, 18)); // NOI18N
        lbl_question_number.setText("Question # 1");

        btn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next_icon_1.png"))); // NOI18N
        btn_next.setContentAreaFilled(false);
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_question_headLayout = new javax.swing.GroupLayout(panel_question_head);
        panel_question_head.setLayout(panel_question_headLayout);
        panel_question_headLayout.setHorizontalGroup(
            panel_question_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_headLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_question_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_question_headLayout.createSequentialGroup()
                        .addGroup(panel_question_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_student_number)
                            .addGroup(panel_question_headLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_time)))
                        .addGap(122, 122, 122)
                        .addComponent(lbl_question_number))
                    .addGroup(panel_question_headLayout.createSequentialGroup()
                        .addComponent(lbl_name)
                        .addGap(147, 147, 147)
                        .addComponent(lbl_subject)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_next))
        );
        panel_question_headLayout.setVerticalGroup(
            panel_question_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_question_headLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_question_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_next)
                    .addGroup(panel_question_headLayout.createSequentialGroup()
                        .addGroup(panel_question_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_name)
                            .addComponent(lbl_subject))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_question_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_question_number)
                            .addGroup(panel_question_headLayout.createSequentialGroup()
                                .addComponent(lbl_student_number)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_question_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(lbl_time)))))))
        );

        panel_question_body.setBackground(new java.awt.Color(204, 153, 0));
        panel_question_body.setLayout(new java.awt.CardLayout());

        panel_question_body_1.setBackground(new java.awt.Color(204, 153, 0));

        jLabel7.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jLabel7.setText("<html>Which of the following comparison operators could be used <br \\>in a multiple row query?");

        buttonGroup1.add(radioBtn_answer_1);
        radioBtn_answer_1.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        radioBtn_answer_1.setText("All of the above ");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton2.setText("ALL operator ");

        buttonGroup1.add(radioBtn_3);
        radioBtn_3.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        radioBtn_3.setText("ANY operator ");

        buttonGroup1.add(radioBtn_answer_1512);
        radioBtn_answer_1512.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        radioBtn_answer_1512.setText("IN operator ");

        javax.swing.GroupLayout panel_question_body_1Layout = new javax.swing.GroupLayout(panel_question_body_1);
        panel_question_body_1.setLayout(panel_question_body_1Layout);
        panel_question_body_1Layout.setHorizontalGroup(
            panel_question_body_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_question_body_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioBtn_answer_1)
                    .addComponent(jRadioButton2)
                    .addComponent(radioBtn_3)
                    .addComponent(radioBtn_answer_1512))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        panel_question_body_1Layout.setVerticalGroup(
            panel_question_body_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioBtn_answer_1512)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtn_answer_1)
                .addGap(22, 22, 22))
        );

        panel_question_body.add(panel_question_body_1, "card2");

        panel_question_body_2.setBackground(new java.awt.Color(204, 153, 0));

        jLabel8.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jLabel8.setText("Which of the following is not true about complex views?");

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton6.setText("All of the above are true.");

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton7.setText("You cannot perform DML operations through a complex view.");

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton8.setText("They derive data from more than one table.");

        buttonGroup2.add(radioBtn_answer_2);
        radioBtn_answer_2.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        radioBtn_answer_2.setText("They contain no functions or grouping.");

        javax.swing.GroupLayout panel_question_body_2Layout = new javax.swing.GroupLayout(panel_question_body_2);
        panel_question_body_2.setLayout(panel_question_body_2Layout);
        panel_question_body_2Layout.setHorizontalGroup(
            panel_question_body_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_question_body_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8)
                    .addComponent(radioBtn_answer_2))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panel_question_body_2Layout.setVerticalGroup(
            panel_question_body_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(radioBtn_answer_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6)
                .addGap(22, 22, 22))
        );

        panel_question_body.add(panel_question_body_2, "card2");

        panel_question_body_3.setBackground(new java.awt.Color(204, 153, 0));

        jLabel9.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jLabel9.setText("A transaction starts when");

        buttonGroup3.add(radioBtn_answer_3);
        radioBtn_answer_3.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        radioBtn_answer_3.setText("All of the above");

        buttonGroup3.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton11.setText("A CREATE statement is used");

        buttonGroup3.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton12.setText("A ROLLBACK statement is issued");

        buttonGroup3.add(radioBtn_4);
        radioBtn_4.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        radioBtn_4.setText("A COMMIT statement is issued");

        javax.swing.GroupLayout panel_question_body_3Layout = new javax.swing.GroupLayout(panel_question_body_3);
        panel_question_body_3.setLayout(panel_question_body_3Layout);
        panel_question_body_3Layout.setHorizontalGroup(
            panel_question_body_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_question_body_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(radioBtn_answer_3)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12)
                    .addComponent(radioBtn_4))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        panel_question_body_3Layout.setVerticalGroup(
            panel_question_body_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioBtn_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtn_answer_3)
                .addGap(22, 22, 22))
        );

        panel_question_body.add(panel_question_body_3, "card2");

        panel_question_body_4.setBackground(new java.awt.Color(204, 153, 0));

        jLabel10.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jLabel10.setText("What does SQL stand for");

        buttonGroup4.add(jRadioButton14);
        jRadioButton14.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton14.setText("Small Quick Language");

        buttonGroup4.add(jRadioButton15);
        jRadioButton15.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton15.setText("Structured Question Language");

        buttonGroup4.add(radioBtn_answer_4);
        radioBtn_answer_4.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        radioBtn_answer_4.setText("Structured Query Language");

        buttonGroup4.add(radioBtn09);
        radioBtn09.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        radioBtn09.setText("Strong Question Language");

        javax.swing.GroupLayout panel_question_body_4Layout = new javax.swing.GroupLayout(panel_question_body_4);
        panel_question_body_4.setLayout(panel_question_body_4Layout);
        panel_question_body_4Layout.setHorizontalGroup(
            panel_question_body_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_question_body_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton15)
                    .addComponent(radioBtn_answer_4)
                    .addComponent(radioBtn09))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        panel_question_body_4Layout.setVerticalGroup(
            panel_question_body_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioBtn09)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtn_answer_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton14)
                .addGap(22, 22, 22))
        );

        panel_question_body.add(panel_question_body_4, "card2");

        panel_question_body_5.setBackground(new java.awt.Color(204, 153, 0));

        jLabel11.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jLabel11.setText("<html>Which of the following statements allows William to change his <br \\ >database user account password to bill?");

        buttonGroup5.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton3.setText("alter user william identified by bill");

        buttonGroup5.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton4.setText("create user william password bill;");

        buttonGroup5.add(radioBtn_answer_5);
        radioBtn_answer_5.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        radioBtn_answer_5.setText("alter user william password bill;");

        buttonGroup5.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jRadioButton9.setText("create user william identified by bill;");

        javax.swing.GroupLayout panel_question_body_5Layout = new javax.swing.GroupLayout(panel_question_body_5);
        panel_question_body_5.setLayout(panel_question_body_5Layout);
        panel_question_body_5Layout.setHorizontalGroup(
            panel_question_body_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_question_body_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton4)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3)
                    .addComponent(radioBtn_answer_5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_question_body_5Layout.setVerticalGroup(
            panel_question_body_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question_body_5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtn_answer_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addGap(22, 22, 22))
        );

        panel_question_body.add(panel_question_body_5, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_question_body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_question_head, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_question_head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_question_body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
        lbl_question_number.setText("Question # " + itr);
        if(itr == 2){
            getData(panel_question_body, panel_question_body_2);
        }
        else if(itr == 3){
            getData(panel_question_body, panel_question_body_3);
        }
        else if(itr == 4){
            getData(panel_question_body, panel_question_body_4);
        }
        else if(itr == 5){
            getData(panel_question_body, panel_question_body_5);
        }
        else{
            int score = 0;

            if(radioBtn_answer_1.isSelected()){
                score++;
            }
            if(radioBtn_answer_2.isSelected()){
                score++;
            }
            if(radioBtn_answer_3.isSelected()){
                score++;
            }
            if(radioBtn_answer_4.isSelected()){
                score++;
            }
            if(radioBtn_answer_5.isSelected()){
                score++;
            }

            insertData(score);
            nextFrame();
        }
        itr++;
    }//GEN-LAST:event_btn_nextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_next;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_question_number;
    private javax.swing.JLabel lbl_student_number;
    private javax.swing.JLabel lbl_subject;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JPanel panel_question_body;
    private javax.swing.JPanel panel_question_body_1;
    private javax.swing.JPanel panel_question_body_2;
    private javax.swing.JPanel panel_question_body_3;
    private javax.swing.JPanel panel_question_body_4;
    private javax.swing.JPanel panel_question_body_5;
    private javax.swing.JPanel panel_question_head;
    private javax.swing.JRadioButton radioBtn09;
    private javax.swing.JRadioButton radioBtn_3;
    private javax.swing.JRadioButton radioBtn_4;
    private javax.swing.JRadioButton radioBtn_answer_1;
    private javax.swing.JRadioButton radioBtn_answer_1512;
    private javax.swing.JRadioButton radioBtn_answer_2;
    private javax.swing.JRadioButton radioBtn_answer_3;
    private javax.swing.JRadioButton radioBtn_answer_4;
    private javax.swing.JRadioButton radioBtn_answer_5;
    // End of variables declaration//GEN-END:variables
}
