/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DatabaseManager;

/**
 *
 * @author EJ
 */
public class AdminActions extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdminActions
     */
    public AdminActions() {
        initComponents();
         remove_Border_And_Titlebar();
    }
    
    public void remove_Border_And_Titlebar(){
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Verification = new javax.swing.JButton();
        btn_student = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_results = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 390));
        setMinimumSize(new java.awt.Dimension(850, 390));
        setPreferredSize(new java.awt.Dimension(850, 390));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Verification.setBackground(new java.awt.Color(0, 0, 0));
        btn_Verification.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        btn_Verification.setForeground(new java.awt.Color(240, 240, 240));
        btn_Verification.setText("Verification");
        btn_Verification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerificationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Verification, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 111, 261, -1));

        btn_student.setBackground(new java.awt.Color(0, 0, 0));
        btn_student.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        btn_student.setForeground(new java.awt.Color(240, 240, 240));
        btn_student.setText("Student Information");
        btn_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_studentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 172, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_icon.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 60, 60));

        btn_results.setBackground(new java.awt.Color(0, 0, 0));
        btn_results.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        btn_results.setForeground(new java.awt.Color(240, 240, 240));
        btn_results.setText("Results");
        btn_results.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resultsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_results, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 233, 261, -1));

        jLabel1.setFont(new java.awt.Font("Forte", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Admin Actions");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 11, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG_4.2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_VerificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerificationActionPerformed
        // TODO add your handling code here:
        Verification vf = new Verification();
        vf.setVisible(true);
        this.getDesktopPane().add(vf);
        this.dispose();
    }//GEN-LAST:event_btn_VerificationActionPerformed

    private void btn_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_studentActionPerformed
        // TODO add your handling code here:
        StudentInfo vf = new StudentInfo();
        vf.setVisible(true);
        this.getDesktopPane().add(vf);
        this.dispose();                  
    }//GEN-LAST:event_btn_studentActionPerformed

    private void btn_resultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resultsActionPerformed
        // TODO add your handling code here:
        ResultInfo vf = new ResultInfo();
        vf.setVisible(true);
        this.getDesktopPane().add(vf);
        this.dispose();   
    }//GEN-LAST:event_btn_resultsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        OpeningLogin vf = new OpeningLogin();
        vf.setVisible(true);
        this.getDesktopPane().add(vf);
        this.dispose();   
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminActions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminActions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminActions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminActions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminActions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Verification;
    private javax.swing.JButton btn_results;
    private javax.swing.JButton btn_student;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
