/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package DatabaseManager;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author EJ
 */
public class OpeningLogin extends javax.swing.JInternalFrame {
    
    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /** Creates new form JL */
    public OpeningLogin() {
        initComponents();
        connection = mysqlConnection.dbConnector();
        remove_Border_And_Titlebar();
    }
    
    public void remove_Border_And_Titlebar(){
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_student = new javax.swing.JToggleButton();
        btn_admin = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(850, 390));
        setMinimumSize(new java.awt.Dimension(850, 390));
        setPreferredSize(new java.awt.Dimension(850, 390));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_student.setBackground(new java.awt.Color(0, 0, 0));
        btn_student.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        btn_student.setForeground(new java.awt.Color(240, 240, 240));
        btn_student.setText("Student");
        btn_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_studentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 159, 54));

        btn_admin.setBackground(new java.awt.Color(0, 0, 0));
        btn_admin.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        btn_admin.setForeground(new java.awt.Color(240, 240, 240));
        btn_admin.setText("Admin");
        btn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminActionPerformed(evt);
            }
        });
        getContentPane().add(btn_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 159, 54));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Forte", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, 52));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG_4.2.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(830, 350));
        jLabel2.setMinimumSize(new java.awt.Dimension(830, 350));
        jLabel2.setPreferredSize(new java.awt.Dimension(830, 350));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_studentActionPerformed
        // TODO add your handling code here:
        StudentLogin rf = new StudentLogin();
        rf.setVisible(true);
        this.getDesktopPane().add(rf);
        this.dispose();
    }//GEN-LAST:event_btn_studentActionPerformed

    private void btn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminActionPerformed
        // TODO add your handling code here:
        AdminLogin al = new AdminLogin();
        al.setVisible(true);
        this.getDesktopPane().add(al);
        this.dispose();
    }//GEN-LAST:event_btn_adminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_admin;
    private javax.swing.JToggleButton btn_student;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
