/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DatabaseManager;

import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author EJ
 */
public class Registration extends javax.swing.JInternalFrame {
    
    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st = null;
    private String date;
    private String time;    
    /**
     * Creates new form NewJInternalFrame
     */
    public Registration() {
        initComponents();
        connection = mysqlConnection.dbConnector();
        remove_Border_And_Titlebar();
        getCurrentDateTime();
    }
    
    public void remove_Border_And_Titlebar(){
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }
    
     private void clear(){
        txt_username.setText("");
        txt_first_name.setText("");
        txt_password.setText("");
        txt_last_name.setText("");
        txt_email.setText("");
        comboBox_program.setSelectedIndex(0);
    }
    
     public void getCurrentDateTime(){
      Thread clock = new Thread(){
          public void run(){
              for(;;){
                  Calendar cal = new GregorianCalendar();
                  int month = cal.get(Calendar.MONTH);
                  int year = cal.get(Calendar.YEAR);
                  int day = cal.get(Calendar.DAY_OF_MONTH);
                  date = (year + "/" + (month+1) + "/" + day);
                  menu_date.setText("Date: " + year + "/" + (month+1) + "/" + day); 

                  int second = cal.get(Calendar.SECOND);
                  int minute = cal.get(Calendar.MINUTE);
                  int hour = cal.get(Calendar.HOUR);
                  time = (hour + ":" + minute + ":" + second);
                  menu_time.setText("Time: " + hour + ":" + minute + ":" + second);
                  try {
                      sleep(1000);
                  } catch (InterruptedException ex) {
                      Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
                  }
              }
          }
      };
      clock.start();
    }
     
    public boolean isFieldEmpty(){
        return txt_username.getText().isEmpty() ||
            txt_password.getText().isEmpty() ||
            txt_first_name.getText().isEmpty() ||
            txt_last_name.getText().isEmpty() ||
            txt_email.getText().isEmpty() ||
            comboBox_program.getSelectedItem().equals("");
    }
    
   public boolean isUsernameExist(){
       String username = txt_username.getText();
       
       try{
           String sql = "select * from Student where username =?";
           pst = connection.prepareStatement(sql);
           pst.setString(1, username);
           rs = pst.executeQuery();
           
           if(rs.next()){
               return true;
           }
           rs.close();
           pst.close();
       }catch(Exception e){
           e.printStackTrace();
       }
       return false;
   }
   
   public boolean isNameExist(){
       String first_name = txt_first_name.getText();
       String last_name = txt_last_name.getText();
       
       try{
           String sql = "select * from Student where `First name` =? and `Last name` = ? ";
           pst = connection.prepareStatement(sql);
           pst.setString(1, first_name);
           pst.setString(2, last_name);
           rs = pst.executeQuery();
           
           if(rs.next()){
               return true;
           }
           rs.close();
           pst.close();
       }catch(Exception e){
           e.printStackTrace();
       }
       return false;
   }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();
        txt_username = new javax.swing.JTextField();
        txt_first_name = new javax.swing.JTextField();
        txt_last_name = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        comboBox_program = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        menu_date = new javax.swing.JMenu();
        menu_time = new javax.swing.JMenu();

        setMaximumSize(new java.awt.Dimension(850, 390));
        setMinimumSize(new java.awt.Dimension(850, 390));
        setPreferredSize(new java.awt.Dimension(850, 390));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("First name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Last name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Program");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, 30));

        btn_back.setBackground(new java.awt.Color(0, 0, 0));
        btn_back.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(240, 240, 240));
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 130, 40));

        btn_submit.setBackground(new java.awt.Color(0, 0, 0));
        btn_submit.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(240, 240, 240));
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 130, 40));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 130, 30));
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 130, 30));
        getContentPane().add(txt_first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 130, 30));
        getContentPane().add(txt_last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 130, 30));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 130, 30));

        comboBox_program.setBackground(new java.awt.Color(0, 0, 0));
        comboBox_program.setFont(new java.awt.Font("Forte", 1, 14)); // NOI18N
        comboBox_program.setForeground(new java.awt.Color(240, 240, 240));
        comboBox_program.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","BSCS", "BSIT", "BSIS"}));
        getContentPane().add(comboBox_program, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 130, 30));

        jLabel7.setFont(new java.awt.Font("Forte", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Registration Form");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Username");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG_4.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 350));

        menu_date.setBackground(new java.awt.Color(0, 0, 0));
        menu_date.setText("Date");
        menu_date.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        MenuBar.add(menu_date);

        menu_time.setText("Time");
        menu_time.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        MenuBar.add(menu_time);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        OpeningLogin al = new OpeningLogin();
        al.setVisible(true);
        this.getDesktopPane().add(al);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        if(isUsernameExist()){
           JOptionPane.showMessageDialog(null, "Username is already exists!"); 
        }
        else if(isNameExist()){
            JOptionPane.showMessageDialog(null, "You already registered!"); 
        }
        else if(isFieldEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in required fields!"); 
        }
        else{
            try{
                String sql = "insert into Student (`Registered Date`, Username, Password, `First name`, `Last name`, Email, Program) "
                        + "values(?,?,?,upper(?),upper(?),?,?)";
                pst = connection.prepareCall(sql);

                String registered_date = "Date: " + date + " " + "Time: " + time;
                pst.setString(1, registered_date);
                pst.setString(2, txt_username.getText());
                pst.setString(3, txt_password.getText());
                pst.setString(4, txt_first_name.getText());
                pst.setString(5, txt_last_name.getText());
                pst.setString(6, txt_email.getText());
                String program = comboBox_program.getSelectedItem().toString();
                pst.setString(7, program);

                JOptionPane.showMessageDialog(null, "Data Saved");
                pst.execute();
                pst.close();
                clear();
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_submitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> comboBox_program;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu menu_date;
    private javax.swing.JMenu menu_time;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_first_name;
    private javax.swing.JTextField txt_last_name;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
