/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DatabaseManager;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author EJ
 */
public class ResultInfo extends javax.swing.JInternalFrame {
    
    Connection connection = null;
    PreparedStatement pst = null; 
    ResultSet rs = null; 
    Statement st = null;
    /**
     * Creates new form ResultInfo
     */
    public ResultInfo() {
        initComponents();
        connection = mysqlConnection.dbConnector();
        show_Exam_Table();
        remove_Border_And_Titlebar();
         //byProgram();
        // byAverage();
    }
    
     private void show_Exam_Table(){
        try{
            String sql = "select Date, `Student #`, concat(`last name`, ', ', `first name`) as Name, `Course Code`, Score "
                    + "from Exam natural join Student";
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();
            table_student_info.setModel(DbUtils.resultSetToTableModel(rs));
            
            pst.close();
        }catch(Exception e){
        }
    }
     
    public void byStudent(){
        try{
            String sql = "select concat(`last name`, ', ', `first name`) as Name, Program, sum(score) as `Total Score` "
                    + "from Exam natural join Student group by `student #` "
                    + "order by sum(score) desc";
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();
            table_student_info.setModel(DbUtils.resultSetToTableModel(rs));
            
            pst.close();
            rs.close();
        }catch(Exception e){
        }
    }
     
    public void byProgram(){
        try{
            String sql = "select program, count(distinct(`student #`)) as 'Total Examinees' , "
                    + "sum(score) as 'Total Score', "
                    + "truncate(sum(score)/count(distinct(`student #`)), 0) as 'Average Score' "
                    + "from Exam natural join Student "
                    + "group by program "
                    + "order by sum(score) desc";
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();
            table_student_info.setModel(DbUtils.resultSetToTableModel(rs));
            
            pst.close();
            rs.close();
        }catch(Exception e){
        }
    } 
    
    private void remove_Border_And_Titlebar(){
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }
    public void byAverage(){
        try{
            String sql = "select truncate(avg(theSum)/count(cBSIT), 0) "
                    + "from (select sum(score) as theSum, program as cBSIT from result natural join student group by program having program in ('BSIT') ) "
                    + "result";
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();
            table_student_info.setModel(DbUtils.resultSetToTableModel(rs));
            
            pst.close();
            rs.close();
        }catch(Exception e){
        }
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_student_info = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        comboBox_sort = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 390));
        setMinimumSize(new java.awt.Dimension(850, 390));
        setPreferredSize(new java.awt.Dimension(850, 390));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setMaximumSize(new java.awt.Dimension(810, 292));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(810, 292));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(810, 292));

        table_student_info.setBackground(new java.awt.Color(0, 0, 0));
        table_student_info.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        table_student_info.setForeground(new java.awt.Color(51, 204, 0));
        table_student_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student #", "Name", "Subject", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_student_info);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, -1, 234));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Sort by:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, -1, -1));

        comboBox_sort.setBackground(new java.awt.Color(0, 0, 0));
        comboBox_sort.setFont(new java.awt.Font("Forte", 1, 14)); // NOI18N
        comboBox_sort.setForeground(new java.awt.Color(240, 240, 240));
        comboBox_sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Exam Table", "Student", "Program" }));
        comboBox_sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_sortActionPerformed(evt);
            }
        });
        jPanel2.add(comboBox_sort, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 73, 120, -1));

        jLabel2.setFont(new java.awt.Font("Forte", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("EXAM TABLE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_icon.png"))); // NOI18N
        btn_back.setContentAreaFilled(false);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel2.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG_4.2.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 370));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(889, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void comboBox_sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_sortActionPerformed
        // TODO add your handling code here:
        if(comboBox_sort.getSelectedItem().equals("Student")){
            byStudent();
        }
        else if(comboBox_sort.getSelectedItem().equals("Program")){
            byProgram();
        }
        else if(comboBox_sort.getSelectedItem().equals("Exam Table")){
            show_Exam_Table();
        }
    }//GEN-LAST:event_comboBox_sortActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        AdminActions vf = new AdminActions();
        vf.setVisible(true);
        this.getDesktopPane().add(vf);
        this.dispose();   
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ResultInfo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JComboBox<String> comboBox_sort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_student_info;
    // End of variables declaration//GEN-END:variables
}
