/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DatabaseManager;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author EJ
 */
public class StudentInfo extends javax.swing.JInternalFrame {
Connection connection = null;
PreparedStatement pst = null;
ResultSet rs = null;

    /**
     * Creates new form StudentInfo
     */
    public StudentInfo() {
        initComponents();
        connection = mysqlConnection.dbConnector();
        updateTable();
        setColumnWidth();
         remove_Border_And_Titlebar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    
    public void remove_Border_And_Titlebar(){
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }
    private void byBSCS(){
        try{
            String sql = "select * "
                + "from Student "
                + "where program = 'BSCS' ";
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();
            table_student_info.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void byBSIT(){
        try{
            String sql = "select * "
                + "from Student "
                + "where program = 'BSIT' ";
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();
            table_student_info.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void byBSIS(){
        try{
            String sql = "select * "
                + "from Student "
                + "where program = 'BSIS' ";
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();
            table_student_info.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void setColumnWidth(){
        table_student_info.getColumnModel().getColumn(0).setPreferredWidth(110);
        table_student_info.getColumnModel().getColumn(1).setPreferredWidth(340);
        table_student_info.getColumnModel().getColumn(2).setPreferredWidth(150);
        table_student_info.getColumnModel().getColumn(3).setPreferredWidth(150);
        table_student_info.getColumnModel().getColumn(4).setPreferredWidth(150);
        table_student_info.getColumnModel().getColumn(5).setPreferredWidth(150);
        table_student_info.getColumnModel().getColumn(6).setPreferredWidth(150);
        table_student_info.getColumnModel().getColumn(7).setPreferredWidth(100);
    }
    
    public void updateTable(){
        try{
            String sql = "select `Student #`, `Registered date`, Username, Password, `First name`, `Last name`, Email, Program "
                    + "from student";
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();
            table_student_info.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
            rs.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboBox_sort = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_student_info = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 390));
        setMinimumSize(new java.awt.Dimension(850, 390));
        setPreferredSize(new java.awt.Dimension(850, 390));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboBox_sort.setBackground(new java.awt.Color(0, 0, 0));
        comboBox_sort.setFont(new java.awt.Font("Forte", 1, 14)); // NOI18N
        comboBox_sort.setForeground(new java.awt.Color(240, 240, 240));
        comboBox_sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student Table", "BSCS",  "BSIS", "BSIT" }));
        comboBox_sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_sortActionPerformed(evt);
            }
        });
        jPanel1.add(comboBox_sort, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 140, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Sort by:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jScrollPane2.setMaximumSize(new java.awt.Dimension(810, 292));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(810, 292));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(810, 292));

        table_student_info.setBackground(new java.awt.Color(0, 0, 0));
        table_student_info.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        table_student_info.setForeground(new java.awt.Color(51, 204, 0));
        table_student_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student #", "Registered Date", "Username", "Password", "First name", "Last name", "Email", "Program"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_student_info);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, -1, 240));

        jLabel2.setFont(new java.awt.Font("Forte", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Student Table");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_icon.png"))); // NOI18N
        btn_back.setContentAreaFilled(false);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG_4.2.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 380));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        //TODO add your handling code here:
        AdminActions vf = new AdminActions();
        vf.setVisible(true);
        this.getDesktopPane().add(vf);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void comboBox_sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_sortActionPerformed
        // TODO add your handling code here:
        if(comboBox_sort.getSelectedItem().equals("BSCS")){
            byBSCS();
        }
        else if(comboBox_sort.getSelectedItem().equals("BSIS")){
            byBSIS();
        }
        else if(comboBox_sort.getSelectedItem().equals("BSIT")){
            byBSIT();
        }
        else if(comboBox_sort.getSelectedItem().equals("Student Table")){
            updateTable();
        }
    }//GEN-LAST:event_comboBox_sortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JComboBox<String> comboBox_sort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_student_info;
    // End of variables declaration//GEN-END:variables
}
