/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DatabaseManager;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author EJ
 */
public class Verification extends javax.swing.JInternalFrame {
Connection connection = null;
ResultSet rs = null;
PreparedStatement pst = null;
Statement st = null;
    /**
     * Creates new form Verification
     */
    public Verification() {
        initComponents();
        connection = mysqlConnection.dbConnector();
        Update_table();
        remove_Border_And_Titlebar();
    }
    
    public void remove_Border_And_Titlebar(){
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    
    public ArrayList<Student> getData(){
        ArrayList<Student> studentList = new ArrayList<Student>();
        String sql = "select * from Student";
        
        try{
            st = connection.createStatement();
            rs = st.executeQuery(sql);
            Student student;
            
            while(rs.next()){
                student = new Student(
               
                rs.getInt("student #"),
                rs.getString("username"),
                rs.getString("password"),
                rs.getString("first name"),
                rs.getString("last name"),
                rs.getString("email"),
                rs.getString("program"));
                
                studentList.add(student);
            }
        }catch(SQLException e){
            Logger.getLogger(Verification.class.getName()).log(Level.SEVERE, null, e);
        }
        return studentList;
    }
    
    // Display Data in JTable
    public void showStudentJTable(){
        ArrayList<Student> list = getData();
        DefaultTableModel model = (DefaultTableModel)table_studentList.getModel();
        
        Object[] rowData = new Object[7];
        for(int i = 0; i < getData().size(); i++){
            
            rowData[0] = list.get(i).getStudentNumber();
            rowData[1] = list.get(i).getUsername();
            rowData[2] = list.get(i).getPassword();
            rowData[3] = list.get(i).getFirstName();
            rowData[4] = list.get(i).getLastName();
            rowData[5] = list.get(i).getEmail();
            rowData[6] = list.get(i).getProgram();
        						
        model.addRow(rowData);
        }
    }
    
     public void executeSQLQuery(String query, String message){
       try{
           st = connection.createStatement();
           if((st.executeUpdate(query)) == 1){
               JOptionPane.showMessageDialog(null, "Data " + message);
           }
           else{
               JOptionPane.showMessageDialog(null, "Data not " + message);
           }
       }catch(Exception e){
           e.printStackTrace();
       }
    }
     
    public void Update_table(){
        try{
            String sql = "select `Student #`, Username, Password, `First name`, `Last name`, Email, Program from student";
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();
            table_studentList.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
     private void clear(){
        txt_username.setText("");
        txt_password.setText("");
        txt_first_name.setText("");
        txt_last_name.setText("");
        txt_email.setText("");
        txt_search.setText("");
        lbl_student_number.setText("");
        comboBox_program.setSelectedIndex(0);
    }
     
     public boolean isFieldEmpty(){
        return txt_username.getText().isEmpty() ||
            txt_password.getText().isEmpty() ||
            txt_first_name.getText().isEmpty() ||
            txt_last_name.getText().isEmpty() ||
            txt_email.getText().isEmpty() ||
            comboBox_program.getSelectedItem().equals("");
    }
    
 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        txt_first_name = new javax.swing.JTextField();
        txt_last_name = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        comboBox_program = new javax.swing.JComboBox<>();
        btn_update = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_studentList = new javax.swing.JTable();
        btn_delete = new javax.swing.JButton();
        lbl_student_number = new javax.swing.JLabel();
        jLabel_MainBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 390));
        setMinimumSize(new java.awt.Dimension(850, 390));
        setPreferredSize(new java.awt.Dimension(850, 390));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Forte", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Registration Verification");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 9, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Username");
        jLabel2.setFocusCycleRoot(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Password");
        jLabel3.setFocusCycleRoot(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("First name");
        jLabel6.setFocusCycleRoot(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Last name");
        jLabel7.setFocusCycleRoot(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Student #");
        jLabel5.setFocusCycleRoot(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Email");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Program");
        jLabel8.setFocusCycleRoot(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 112, -1));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 112, -1));
        getContentPane().add(txt_first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 112, -1));
        getContentPane().add(txt_last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 112, -1));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 112, -1));

        comboBox_program.setBackground(new java.awt.Color(0, 0, 0));
        comboBox_program.setFont(new java.awt.Font("Forte", 1, 14)); // NOI18N
        comboBox_program.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"", "BSCS", "BSIT", "BSIS" }));
        getContentPane().add(comboBox_program, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 112, -1));

        btn_update.setBackground(new java.awt.Color(0, 0, 0));
        btn_update.setFont(new java.awt.Font("Forte", 1, 14)); // NOI18N
        btn_update.setForeground(new java.awt.Color(240, 240, 240));
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, 34));

        btn_back.setBackground(new java.awt.Color(0, 0, 0));
        btn_back.setFont(new java.awt.Font("Forte", 1, 14)); // NOI18N
        btn_back.setForeground(new java.awt.Color(240, 240, 240));
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 83, 34));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Search");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, -1, 50));

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        getContentPane().add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 130, -1));

        table_studentList.setBackground(new java.awt.Color(0, 0, 0));
        table_studentList.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        table_studentList.setForeground(new java.awt.Color(0, 204, 0));
        table_studentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student #", "Username", "Password", "First name", "Last name", "Email", "Program"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_studentList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_studentListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_studentList);
        if (table_studentList.getColumnModel().getColumnCount() > 0) {
            table_studentList.getColumnModel().getColumn(0).setHeaderValue("Student #");
            table_studentList.getColumnModel().getColumn(1).setHeaderValue("Username");
            table_studentList.getColumnModel().getColumn(2).setHeaderValue("Password");
            table_studentList.getColumnModel().getColumn(3).setHeaderValue("First name");
            table_studentList.getColumnModel().getColumn(4).setHeaderValue("Last name");
            table_studentList.getColumnModel().getColumn(5).setHeaderValue("Email");
            table_studentList.getColumnModel().getColumn(6).setHeaderValue("Program");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 500, 240));

        btn_delete.setBackground(new java.awt.Color(0, 0, 0));
        btn_delete.setFont(new java.awt.Font("Forte", 1, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(240, 240, 240));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 83, 35));

        lbl_student_number.setText("#");
        getContentPane().add(lbl_student_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 112, 20));

        jLabel_MainBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG_4.jpg"))); // NOI18N
        getContentPane().add(jLabel_MainBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        AdminActions rf = new AdminActions();
        rf.setVisible(true);
        this.getDesktopPane().add(rf);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed
    
    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        String value1 = txt_username.getText();
        String value2 = txt_password.getText();
        String value3 = txt_first_name.getText();
        String value4 = txt_last_name.getText();
        String value5 = lbl_student_number.getText();
        String value6 = txt_email.getText();
        String value7 = comboBox_program.getSelectedItem().toString();
        
        if(isFieldEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill up required fields!");
        }
        else{
            String sql ="update Student set username='"+value1+"'"
                   + " ,password='"+value2+"'"
                   + " ,`first name`=upper('"+value3+"')"
                   + " ,`last name`=upper('"+value4+"')"
                   + " ,email='"+value6+"'"
                   + " ,program='"+value7+"'"
                   + " where `student #`='"+value5+"' ";
            try {
                pst = connection.prepareStatement(sql);
                pst.execute();
                pst.close();
                JOptionPane.showMessageDialog(null, "Data Updated");
                
            } catch (SQLException ex) {
                Logger.getLogger(Verification.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            Update_table();
            clear();
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void table_studentListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_studentListMouseClicked
        // TODO add your handling code here:
        int row = table_studentList.getSelectedRow();
        TableModel model = table_studentList.getModel();
        lbl_student_number.setText(model.getValueAt(row, 0).toString());
        txt_username.setText(model.getValueAt(row, 1).toString());
        txt_password.setText(model.getValueAt(row, 2).toString());
        txt_first_name.setText(model.getValueAt(row, 3).toString());
        txt_last_name.setText(model.getValueAt(row, 4).toString());
        txt_email.setText(model.getValueAt(row, 5).toString());
        comboBox_program.setSelectedItem(model.getValueAt(row, 6).toString());
        
    }//GEN-LAST:event_table_studentListMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        String sql = "delete from Student where `student #` = "+lbl_student_number.getText();
        try{
            pst = connection.prepareStatement(sql);
            JOptionPane.showMessageDialog(null, "Data Deleted");
            pst.execute();
            pst.close();
        }catch(Exception e){
            e.printStackTrace();
        }
        Update_table();
        clear();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        String sql = "select * from Student where `Student #`=?";
        try{
            
            pst = connection.prepareStatement(sql);
            pst.setString(1, txt_search.getText());
            rs = pst.executeQuery();
            
            if(rs.next()){
                String value1 = rs.getString("student #");
                lbl_student_number.setText(value1);
                String value2 = rs.getString("username");
                txt_username.setText(value2);
                String value3 = rs.getString("password");
                txt_password.setText(value3);
                String value4 = rs.getString("first name");
                txt_first_name.setText(value4);
                String value5 = rs.getString("last name");
                txt_last_name.setText(value5);
                String value6 = rs.getString("email");
                txt_email.setText(value6);
                String value7 = rs.getString("program");              
                comboBox_program.setSelectedItem(value7);
            }
            
            pst.close();
            rs.close();
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_searchKeyReleased
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Verification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> comboBox_program;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_MainBG;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_student_number;
    private javax.swing.JTable table_studentList;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_first_name;
    private javax.swing.JTextField txt_last_name;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
